name: Deploy Storybook to GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0"

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages

      - name: Comment on PR with Storybook Link
        if: success()
        env:
          PR_URL: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "🚀 Storybook preview available at: $PR_URL"
