name: Cleanup PR Directories

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Delete PR Directory
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          git checkout gh-pages
          rm -rf pr/$PR_NUMBER
          git add .
          git commit -m "Cleanup PR #$PR_NUMBER directory"
          git push origin gh-pages
