name: Cleanup PR Directories

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if gh-pages Branch Exists
        run: |
          if git ls-remote --exit-code origin gh-pages; then
            echo "gh-pages branch exists."
            echo "::set-output name=GH_PAGES_EXISTS::true"
          else
            echo "gh-pages branch does not exist."
            echo "::set-output name=GH_PAGES_EXISTS::false"
          fi
        id: check_branch

      - name: Fetch gh-pages Branch
        if: steps.check_branch.outputs.GH_PAGES_EXISTS == 'true'
        run: |
          git fetch origin gh-pages

      - name: Switch to gh-pages Branch
        if: steps.check_branch.outputs.GH_PAGES_EXISTS == 'true'
        run: |
          git checkout gh-pages

      - name: Configure Git
        if: steps.check_branch.outputs.GH_PAGES_EXISTS == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Delete PR Directory
        if: steps.check_branch.outputs.GH_PAGES_EXISTS == 'true'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          rm -rf pr/$PR_NUMBER
          git add .
          git commit -m "Cleanup PR #$PR_NUMBER directory" || echo "No changes to commit"
          git push origin gh-pages
